### ISSUE TITLE
Documentation link is a 404 not found

### ISSUE THREAD

**Issue by afaur** [RPG-Paper-Maker/RPG-Paper-Maker#10]
Documentation [link](https://github.com/RPG-Paper-Maker/RPG-Paper-Maker/blob/develop/README.md#documentation) in the readme takes you to a 404 page.

It currently links to http://rpgpapermaker.gq/index.php/documentation which does not resolve.

**Comment by Wano-k** [comment]
Thanks, solved simply by changing the domain name (recently changed to a .com one)! 

Referenced commit: 955fc471da29bc70300dbd0bf84113f41c619ab1
