### ISSUE TITLE
RPM 0.4.0 Beta Hangs On Run (OSX 10.12.6)

### ISSUE THREAD

**Issue by afaur** [RPG-Paper-Maker/RPG-Paper-Maker#12]
After building the application from source on OSX 10.12.6 the application hangs on startup.
After running dtruss to diagnose I get the following information...

```
-> % sudo dtruss -n RPG-Paper-Maker
...
11074/0x296ce:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 Err#-2
11074/0x296ec:  workq_kernreturn(0x40, 0x70000EF24B80, 0x1)		 = 0 Err#-2

# This line repeats infinitely and is where the program hangs...
11074/0x296bc:  unlink("/Users/user/RPG-Paper-Maker-v-0.4.0-beta/RPG-Paper-Maker.app\0", 0x7FFF5B050F88, 0x7FFF5B050BC0)		 = -1 Err#1
11074/0x296bc:  ...
11074/0x296bc:  ...

dtrace: error on enabled probe ID 2129 (ID 332: syscall::unlink:return): invalid address (0x0) in action #12 at DIF offset 24
dtrace: 4969 dynamic variable drops with non-empty dirty list
```

I can only guess that the addresses (0x7FFF5B050F88, 0x7FFF5B050BC0) have
something to do with this that I don't fully understand. Could it maybe mean that
it is trying to remove something that should reside inside the application bundle?

Since osx builds an app bundle that holds the binary inside of it (inside of
some nested folders) as opposed to linux (only produces a binary) and windows
(produces an exe) perhaps this is causing an issue?

**Comment by Wano-k** [comment]
Why are you getting such a behaviour ... wasn't it running well in a previous version (at least opening the window)? I will hardly think on the new features that could be doing that, but I don't see it right now. Sending me a tree of your build folder could help! Thanks. :)

**Comment by afaur** [comment]
Yes this seems strange since it did work before. Going to close this and will try some of your suggestions when I do a new build.
