### ISSUE TITLE
please help start failed

### ISSUE THREAD

**Issue by wskongdesheng** [RPG-Paper-Maker/RPG-Paper-Maker#13]
In file included from moc_dialogcollisions.cpp:9:
In file included from ./../RPG-Paper-Maker/Dialogs/dialogcollisions.h:24:
In file included from ../RPG-Paper-Maker/Models/System/systemtileset.h:24:
../RPG-Paper-Maker/Models/System/systempicture.h:52:18: warning: 'SystemPicture::setCopy' hides overloaded virtual function [-Woverloaded-virtual]
virtual void setCopy(const SystemPicture &super);
^
../RPG-Paper-Maker/Models/superlistitem.h:56:18: note: hidden overloaded virtual function 'SuperListItem::setCopy' declared here: type mismatch at 1st parameter ('const SuperListItem &' vs 'const SystemPicture &')
virtual void setCopy(const SuperListItem& item);
^
In file included from moc_dialogcollisions.cpp:9:
In file included from ./../RPG-Paper-Maker/Dialogs/dialogcollisions.h:24:
../RPG-Paper-Maker/Models/System/systemtileset.h:63:18: warning: 'SystemTileset::setCopy' hides overloaded virtual function [-Woverloaded-virtual]
virtual void setCopy(const SystemTileset &super);
^
../RPG-Paper-Maker/Models/superlistitem.h:56:18: note: hidden overloaded virtual function 'SuperListItem::setCopy' declared here: type mismatch at 1st parameter ('const SuperListItem &' vs 'const SystemTileset &')
virtual void setCopy(const SuperListItem& item);
^
2 warnings generated.
In file included from moc_widgettilesetdirection.cpp:9:
In file included from ./../RPG-Paper-Maker/CustomWidgets/widgettilesetdirection.h:25:
../RPG-Paper-Maker/Models/System/systempicture.h:52:18: warning: 'SystemPicture::setCopy' hides overloaded virtual function [-Woverloaded-virtual]
virtual void setCopy(const SystemPicture &super);
^
../RPG-Paper-Maker/Models/superlistitem.h:56:18: note: hidden overloaded virtual function 'SuperListItem::setCopy' declared here: type mismatch at 1st parameter ('const SuperListItem &' vs 'const SystemPicture &')
virtual void setCopy(const SuperListItem& item);
^
1 warning generated.

**Comment by Wano-k** [comment]
What you printed here seems to only be warnings (strange that I never get these ones). Is that your complete console output?

**Comment by wskongdesheng** [comment]
Hi, thanks for your response, what gcc version do you use and what qt version do you use?
Can you speak chinese？
Best
Clark Kong

**Comment by Wano-k** [comment]
Here are my versions:
gcc: 5.4.0
Qt: 5.10.1

Sorry, I can't speak chinese!

**Comment by wskongdesheng** [comment]
Hi, I changed to windows and it works, by the way, how to make this multiple players ?
Thanks
Clark King

**Comment by Wano-k** [comment]
Oops sorry for the late answer. Currently I have no idea how to make this multiple players, but it is for sure possible. Anyway it's not a feature with high priority.
