### ISSUE TITLE
[Bugs] 3 Bugs on v0.5.0 Linux

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#14]
Hello @Wano-k , sorry for late posting. I think you already know this bugs, but I want report it.

The video:
https://youtu.be/DBgzdIfyTPk

______________________________________________
RPG Paper Maker v0.5.0 Error Message on Terminal:

1st Bug: Segmentation fault (core dumped)
2nd Bug: -
3rd Bug: 
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
______________________________________________
My System Specs:

OS: Linux Ubuntu 16.04 LTS 64-Bit (On Asus Laptop)
Memory: 1.9 GiB
Processor: Intel® Core™ i3-2330M CPU @ 2.20GHz × 4
Graphics: Intel® Sandybridge Mobile

**Comment by Wano-k** [comment]
Done, will be deployed for 0.5.2!
