### ISSUE TITLE
[Help] Please Help Fixing my Map (v0.5.0)

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#15]
Hello, yesterday (29 May 2018) I converted map from v0.4.3 and make map in it. Then I add teleport event and collisions to trees and character. But I always have this error message pop-up when try start the game when the teleportation event on map. After I deleted teleportation event, the game start normal.

Then I try other project from v0.4.3 it runs normal, no error message show. Please help, I don't know this is bug or not and I don't know how to fix this.

This is the error message:
![screenshot from 2018-05-29 22-51-02](https://user-images.githubusercontent.com/27815899/40703130-6b40db8a-640e-11e8-8307-a83feb0b65de.png)

This is the project file:
https://drive.google.com/file/d/13gfd7K71l_7omK7_5wf_FxSacghOVb1y/view?usp=sharing
__________________________________________________________________________
My System Specs:

OS: Linux Ubuntu 16.04 LTS 64-Bit (On Asus Laptop)
Memory: 1.9 GiB
Processor: Intel® Core™ i3-2330M CPU @ 2.20GHz × 4
Graphics: Intel® Sandybridge Mobile

**Comment by Wano-k** [comment]
Solved.

Forum subject: http://rpg-paper-maker.com/index.php/forum/general-discuss/45-help-please-help-fixing-my-map-v0-5-0#114

Commit: https://github.com/RPG-Paper-Maker/Game-Scripts/commit/5b171136de477e6832fd46b7211a2301177f0d61
