### ISSUE TITLE
[Bugs] 0.5.1 Linux

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#17]
Hello, I'm back again. I found 2 old bugs from previous version. This is the link: https://github.com/RPG-Paper-Maker/RPG-Paper-Maker/issues/14 . I just remembering you. The bugs is model bugs and armor bugs. And if that video is not too clear I can record it again.

_________________________________________________________________________________
My System Specs:

OS: Linux Ubuntu 16.04 LTS 64-Bit (On Asus Laptop)
Memory: 1.9 GiB
Processor: Intel® Core™ i3-2330M CPU @ 2.20GHz × 4
Graphics: Intel® Sandybridge Mobile

**Comment by Wano-k** [comment]
Done, will be deployed for 0.5.2!
