### ISSUE TITLE
[Linux Bug] 0.5.1 : Broken Collisions on Exported Standalone Game

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#19]
Hello, today (12 July 2018) I try to export my test game as standalone game, I export it to Linux and Windows. When I open the Linux version the collisions is broken, so I can walk through tree, character,etc. Then I try the Windows version using Wine, but I can't open it, the error message is pop-up, but I think this is Wine error.

So, if you not busy please try this bug. And thank you for reading this.

________________________________________________________________
My System Specs:
OS: Ubuntu 16.04 LTS 64-Bit (on Asus Laptop)
Memory: 2 Gb RAM
Processor: Intel® Core™ i3-2330M CPU @ 2.20GHz × 4
Graphics: Intel® Sandybridge Mobile

**Comment by Wano-k** [comment]
Corrected for 1.1.1!
