### ISSUE TITLE
Automated tests and releases

### ISSUE THREAD

**Issue by afaur** [RPG-Paper-Maker/RPG-Paper-Maker#2]
Automated `test` runs, and `release` builds using `travis-ci` and `appveyor` could assist with development and maintaining the project as it grows.

Travis CI
- http://www.travis-ci.org
- `Travis-CI` will:
  - When a `Pull Request` is made by a developer,
    - Set up virtual machines (`Linux` and `OSX`)
    - Pull down down the source from the `branch`
    - Compile, build, and test the code
    - Indicate on the PR if it would introduce breaking changes
  - When a `Tag` is created and pushed to the `repository`
    - Set up virtual machines (`Linux` and `OSX`)
    - Pull down the source from the `tag`
    - Compile, build, test, and publish a `release` to `github`

Appveyor
- https://www.appveyor.com/
- `AppVeyor` will:
  - When a `Pull Request` is made by a developer,
    - Set up a virtual machine (`Windows`)
    - Pull down down the source from the `branch`
    - Compile, build, and test the code
    - Indicate on the PR if it would introduce breaking changes
  - When a `Tag` is created and pushed to the `repository`
    - Set up a virtual machine (`Windows`)
    - Pull down the source from the `tag`
    - Compile, build, test, and publish a `release` to `github`

**Comment by afaur** [comment]
I attempted to add `travis-ci` to see how easy it would be to get it setup. It looks like the extra steps in the `Engine.pro` file do not get the right paths for `copy` operation in the `linux` environment...

Build status page:
(https://travis-ci.org/afaur/RPG-Paper-Maker/builds/252091342)

Linux Build status page:
(https://travis-ci.org/afaur/RPG-Paper-Maker/jobs/252091344)

Linux Build status error:
<img width="1021" alt="linux-build-error" src="https://user-images.githubusercontent.com/898523/28031966-cd8c2034-655d-11e7-8564-8f425f8ac5b0.png">

**Comment by Wano-k** [comment]
Nice initiative!

There should not be errors for Linux, I'm mainly working on that OS and never had any problem with it. Looks like a lot of modules are unknown (by looking at the other errors, for example: `Project ERROR: Unknown module(s) in QT: quick qml`).

**Comment by afaur** [comment]
> There should not be errors for Linux, I'm mainly working on that OS and never had any problem with it.

Looks like by default the `shadow build` option is disabled. I was able to recreate this issue locally by disabling the `shadow build` option and attempting to re-build the `Engine` project. (when you run qt creator it turns this option on for you, but since we don't have access to it in the virtual machine it will be disabled by default)

<img width="850" alt="uncheck-shadow-build" src="https://user-images.githubusercontent.com/898523/28036083-c31198ce-656b-11e7-8588-ee6fd6916bcf.png">

<img width="1062" alt="build-fails" src="https://user-images.githubusercontent.com/898523/28036084-c7fa0a2e-656b-11e7-9cb8-56315e373db7.png">

I think I can fix this by following steps outlined here (https://forum.qt.io/topic/40108/how-to-specify-shadow-build-true-and-set-build-directory-in-the-pro-file/9) however it might be a good idea to update the `.pro` file so that it does not error when `shadow-build` option is set to `false`.

I think the variable `$$OUT_PWD` (http://doc.qt.io/qt-5/qmake-variable-reference.html#out-pwd) is where the `makefile` gets generated. Which turns out to be the same directory as the source code when `shadow build` is disabled (http://doc.qt.io/qtcreator/creator-glossary.html#glossary-shadow-build). That may be the reason the error that is happening.

> Looks like a lot of modules are unknown (by looking at the other errors, for example: Project ERROR: Unknown module(s) in QT: quick qml).

Yes, looks like I should add `qtdeclarative5-dev` based on (https://github.com/splintermind/Dwarf-Therapist/issues/111) (https://packages.ubuntu.com/trusty/qtdeclarative5-dev)

**Comment by afaur** [comment]
Could suppress the copy command error code possibly using this.
(https://serverfault.com/questions/153875/how-to-let-cp-command-dont-fire-an-error-when-source-file-does-not-exist)

```sh
cp FROM_PATH TO_PATH 2>/dev/null || :
```

**Comment by Wano-k** [comment]
Great, I didn't know that this option existed! I tested on Linux without shadow build and it gave me error too. We could suppress the error as you suggested, but I don't want to suppress it when users have the error even when shadow build is enabled. So here is what I used:

```
!equals(PWD, $${OUT_PWD}) {
    // All the copy stuff
}
```

And it worked for both options.

**Comment by afaur** [comment]
Awesome! I worked a bit to get the `travis-ci` portion of this issue working and opened a PR (https://github.com/Wano-k/RPG-Paper-Maker/pull/3). 

I tried to add detailed instructions on what needs to be completed for the `Wano-k/RPG-Paper-Maker` repository to enable the features.

**Comment by afaur** [comment]
Was able to get the `appveyor` portion of this issue addressed with PR (https://github.com/Wano-k/RPG-Paper-Maker/pull/4). I think that will allow this issue to be closed out after configuring, and pushing up `tags` to the repository to see if it will generate the `artifacts` (binaries for win, mac, and linux).

**Comment by Wano-k** [comment]
I tried the AppVeyor build on the last commit [here](https://github.com/Wano-k/RPG-Paper-Maker/commit/bf12a43c002c1110ee9b7d9058dbbde9eee96acb) and we got this error:

```
Build started
git clone -q --branch=develop https://github.com/Wano-k/RPG-Paper-Maker.git C:\projects\rpg-paper-maker
git checkout -qf bf12a43c002c1110ee9b7d9058dbbde9eee96acb
Running Install scripts
set QTDIR=C:\Qt\5.9\mingw53_32
set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
cd $(PROJECT)
The system cannot find the path specified.
Command exited with code 1
```

**Comment by afaur** [comment]
I saw this and have started debugging it [here](https://github.com/afaur/RPG-Paper-Maker/pull/3) I think I was able to fix the issue, but encountered another one. Looks like it does not find the generated binary...
```sh
mingw32-make[1]: Leaving directory 'C:/projects/rpg-paper-maker/Engine'
7z a %PROJECT%.zip %APPVEYOR_BUILD_FOLDER%/release/%PROJECT%.exe
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
Scanning the drive:
WARNING: The system cannot find the path specified.
C:\projects\rpg-paper-maker\release\Engine.exe
0 files, 0 bytes
Creating archive: Engine.zip
Items to compress: 0
Files read from disk: 0
Archive size: 22 bytes (1 KiB)
Scan WARNINGS for files and folders:
C:\projects\rpg-paper-maker\release\Engine.exe : The system cannot find the path specified.
----------------
Scan WARNINGS: 1
Command exited with code 1
```

I am going to try and resolve this and will open a new PR with a fix.

**Comment by afaur** [comment]
I needed to make a separate repository for the `game` portion of this repository.  I was able to get it to automatically generate the `Win32`, `Linux`, and `OSX` versions of the `Game`.  

I created a Github Team named `RPG-Paper` and invited you to it.  I added the `RPG Paper Game` repository to the team and configured it with `Appveyor` and `Travis-CI`.  

Once you join you should have `admin` access to the Team, and you will be able to create releases.  I put instructions on the `README` on how to queue up a new automatic release deployment.  

When you run the command it will `tag` your current `Branch` or `SHA`, and the automated system will compile the binaries, compress them into an archive, and upload them to the repository [Releases Page](https://github.com/RPG-Paper/RPG-Paper-Game/releases).

**Comment by Wano-k** [comment]
Nice work! I joined the team. But I'm still wondering how the engine will have access to the binaries? We need to have a way to copy them to the `Content` folder of the engine. Is that possible?

**Comment by afaur** [comment]
Your absolutely right to ask about this. I have thought about this a bit, and there are many ways to accomplish this. 

One idea is to setup the `engine` project so that we indicate which tagged version the `game` project it should fetch (since as changes are introduced, new releases of `engine` may only work with a particular released version of the `game` project). 

If that information were kept in a `json` file (maybe a file named version.json) inside of the `engine` project we could add a `bin` folder to the `engine` project with scripts that `travis-ci` and `appveyor` could use. 

The script(s) would:
- Build a binary for the `editor` project
- Read the `version.json` file to determine the latest compatible `game` project release
- Fetch the correct `game` release remotely downloading each OS archive.
- Extract the contents of each archive
- Move the extracted files into the proper folder structure for the `editor` project release
- Compress the folder structure and create a new archive
- Add each OS specific archive bundle to the `release` page of the `editor` project

If this sounds like an okay approach then we can tackle this now.

Here is an example of what the contents of the `version.json` file might look like:
```json
{
  "game": {
    "version": "v0.0.1"
  }
}
```

**Comment by afaur** [comment]
File could also be as simple as:
```json
{
  "game": "v0.0.1"
}
```

**Comment by afaur** [comment]
Could also use this file if we wanted to separate out `BR` (base resources?), and possibly `Pictures` into its own repository.

Benefits of keeping these in a separate repository:
- Makes it easier for graphic designers to submit changes
  - Can `git checkout` the repo locally (to inside of where the `Content` folder lives on their system) and then `commit` and push changes up (incrementing a `version.json` or `changelog.md`)
- It would provide a convenient way for updating `Content` without downloading a new version of the `editor` (and subsequently binaries for the `game`) since a game developer may already have these locally.
- Could add a line to the `version.json` file in the `editor` repo that tracks which version of the `resources` repo we want to be automatically included with the release.
  - It could also keep the hidden `.git` folder inside of bundled archive so when game developers download the `release` and browse to the `Content` folder any asset changes would be tracked with git without any setup.

**Comment by Wano-k** [comment]
Sounds great to me! Except for these last two steps:

> Compress the folder structure and create a new archive
> Add each OS specific archive bundle to the release page of the editor project

The script should only build the project and copy the dependencies from the game repository, not generate a release. Releasing the engine should be a separated script (as for the Game repository).

Is the `version.json` necessary? Couldn't we just fetch the last release?

I'm also OK for the BR (Basic Ressource) separation!

**Comment by afaur** [comment]
> Compress the folder structure and create a new archive
Add each OS specific archive bundle to the release page of the editor project

- > The script should only build the project and copy the dependencies from the game repository, not generate a release. Releasing the engine should be a separated script (as for the Game repository).

I may not understand completely, but I am interested in learning more about the idea of script separation (is this similar to how the new `game` repository has multiple scripts inside the `bin` folder or something different?).  

Could we set up [gitter](https://gitter.im/) for this project? Once added a badge could be added to the `README.md`. It facilitates the ability to have a realtime discussion about the project.  It would also be a way to help others become more involved (would let people openly discuss the project without the opening of issues) .

**Comment by Wano-k** [comment]
Done!

Yeah I just meant something similar to the new game repository. Sorry I thought that you wanted to do all the steps within only one script.

**Comment by afaur** [comment]
Okay, sounds good. I will break it up into different scripts.  I'll make it so it grabs the most recent tagged release from the `game` releases page. If it becomes an issue later then we can add the `version.json` for specifying which one.

**Comment by Wano-k** [comment]
Closing now since no news for almost 5 years. Plus we'll switch to a TypeScript soon.
