### ISSUE TITLE
[Bug] 0.5.3 : Collision Bug After Teleporting Object

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#22]
Hello @Wano-k .

@ rave in the forum said, that, when he/she configure the collision box for character named Kate and make that character teleport using teleport object command, the collision data is left behind, so @ rave is colliding with thin air.

But after I test this bug too, I have slightly different issue. I test the bug using character named Shana, and after the character teleport, I'm not colliding with thin air, I can walk through her body. I'm using the Linux version. This is my screenshot after the character teleport:
![screenshot from 2018-09-18 19-26-49](https://user-images.githubusercontent.com/27815899/45688918-d6453a00-bb7c-11e8-84a6-643a4b5a5386.png)

This is the original post : http://rpg-paper-maker.com/index.php/forum/bug-report/64-when-you-teleport-the-object-it-leaves-its-collision-behind#191

**Comment by Wano-k** [comment]
Corrected for 1.1.1!
