### ISSUE TITLE
[Bug] 0.5.3 : Text Box doesn't Respect New Line Characters.

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#23]
Hello @Wano-k .

@ rave in the forum said, when he/she used show text command to add a multiline message, the in-game it doesn't respect new line characters. 

I test this bug too on my Linux RPM, I have this bug too. I try add this code "\n" or the html br code "< br >" to the text, but not work. This is my screenshot:
![screenshot from 2018-09-18 19-23-08](https://user-images.githubusercontent.com/27815899/45689446-35f01500-bb7e-11e8-84d7-55551517ce27.png)

This is the original post: http://rpg-paper-maker.com/index.php/forum/bug-report/65-text-box-doesn-t-respect-new-line-characters

**Comment by Wano-k** [comment]
Corrected for 1.1.1 release.
