### ISSUE TITLE
[LINUX] RPG Paper Maker editor shows notification when clicking outside active popup

### ISSUE THREAD

**Issue by hsandt** [RPG-Paper-Maker/RPG-Paper-Maker#37]
OS: Linux Ubuntu
Desktop: Gnome
Version: 0.5.3

**Repro**

1. Open a popup window in RPG Paper Maker, such as Datas Manager
2. Click on any area outside the popup

**Result**

The popup blinks and reappears immediately with the notification:

> RPG-Paper-Maker
> "[popup title]" is ready

**Expected**

The app should get focus, with the popup getting localized focus, without blinking.

**Notes**

The bug may come from Qt on Linux itself, need to test a minimal app with a popup on Gnome.

![linux ubuntu gnome - clicking outside popup will show notification popup title is ready develop 2018-09-07](https://user-images.githubusercontent.com/1067772/48317964-4f976100-e5f1-11e8-87d7-a127a72683db.png)

**Comment by Wano-k** [comment]
Still having this? I never had something like that on ubuntu. Are you having this behaviour with other applications?
