### ISSUE TITLE
[WINDOWS] RPG Paper Maker app cannot be focused by clicking outside active popup

### ISSUE THREAD

**Issue by hsandt** [RPG-Paper-Maker/RPG-Paper-Maker#38]
Possibly related to the bug on Linux: https://github.com/RPG-Paper-Maker/RPG-Paper-Maker/issues/37

OS: Windows 10
Version: 0.5.3

**Repro**

1. Open a popup window such as Datas Manager
2. Bring a completely different app to the front, such as File Explorer, but leave some space around to see the RPG Paper Maker app in the background
3. Click on the RPG Paper Maker top-bar or any area outside the active popup itself

**Result**

Windows will play an Invalid operation SFX and not put RPG Paper Maker and its popup window to the front at all.

**Expected**

Focus on RPG Paper Maker, specifically the popup window even if it was not clicked directly. Following Windows convention, it may possibly notify the refocus on the popup itself by a small blinking of the popup topbar color. (but don't overdo it with blinking or it will look like the bug on Linux; and I think the blinking hint was from Windows 7, I'm not sure they do that anymore)

To focus on the app again, you need to either click on the popup area or on the app icon in the tray (or do the keyboard shortcut equivalent).

**Comment by Banbury** [comment]
That's normal behaviour for modal dialogs - at least on windows. I've just tried it with several other programs.

**Comment by hsandt** [comment]
Wow, that seems pretty Windows XP, but OK. I'll try again when I'm back on Windows to also check the SFX.

I have just tested on Gnome and t simply focuses on the popup (say, Firefox Open File popup), with no extra blinking, the popup topbar simply retrieves its full colors to show it is focused.

So for now all we can say is that the Linux variant of the issue is definitely a bug (but may come from Qt and hard to solve). And for other OSes, we may stick to the standard behavior or be bold and break them to improve UX (if we can!)

**Comment by Banbury** [comment]
One could change the dialogs to 'always on top', but then the software has to block interactions with the main window itself.

**Comment by hsandt** [comment]
Actually I've just tried to do the same with a native Windows window like the Open project window (based on File Explorer), and it behaves as I would expect:
1. The "Open a project" window is not considered a separate window in the tray bar. Instead, it is simply a pop up that is part of the main window. Therefore, there is no confusion possible when selecting a window in the tray bar of the switch app menu (alt+tab).
2. Clicking on either the tray icon, the main window behind the popup in the background or the popup itself behind the currently active window will focus on the popup. However, sometimes it will take a small delay before bringing the app to the front, or even not bring it at all unless you go back to the desktop and click on the app icon again.

On the other hand, it seems that the integrated Manager windows use an indirect system to get focus:
1. Manager windows are represented by another window in the tray bar/switch app menu. However, in practice we can only focus on the Manager window, not the main window behind, so there is actually no choice in what we focus.
2. If we select the Manager window from the tray bar/switch app menu, or if we click exactly on the Manager window behind the active window, it will directly show it on top. It will not put the main window to the front. It may be convenient if we want to fill values, say, while watching an Excel sheet in the background, so we don't want the main window (which often takes the whole screen) to appear. In any case it proves that the window is separated.
3. If we select the main window *directly via the tray bar/switch app menu*, the focus will be redirected to the Manager window. At this point the Manager window will mark itself as ready. On Windows, this is rendered by the tray icon blinking (in orange in the dark theme). On Ubuntu with Gnome, we get the "Manager is ready" I mentioned in https://github.com/RPG-Paper-Maker/RPG-Paper-Maker/issues/37. In any case, the whole main window + Manager window on top will appear.
4. Sometimes it's instant, sometimes there is a lag before the windows appear. But it seems to happen in both the Open project integrated popup and the Manager windows, so it may be related to something else specific to the app and not the Manager windows.
5. If we click on the main window behind the currently active window, then we get the error SFX (Windows only) and nothing else happens. (on Linux, behavior is the same as when selecting Main window from tray bar/switch app)

So, to sum-up:
1. Having the Manager windows as a separate window vs an integrated popup is a design choice. The separate window allows the user to only bring the minimum parts of the editor to the front while having other apps on the background to read the values he/she needs.
2. However, when having a separate window, being able to select each window independently would allow even more possibilities. For instance, the user may want to check a few things on the game map in the main window by focusing it once more, before entering values in the Datas Manager. This requires a change in architecture though, as the Manager windows would become async and not prompt-like, and each window would need to refresh its content with any relevant change made on other windows (instead of just refreshing when OK is clicked).
3. If selecting each window individually is not possible, then the behavior should match the integrated popup's behavior closely: clicking on any portion of the app, or selecting any window via tray bar/switch app should focus the Manager window instantly, and not show a Ready notification for more transparent usage. In this case, the only point of having a separate window is that the user can choose to only bring a small Manager window to the front for his/her workflow, instead of the whole app.
4. If we don't mind about the workflow technique mentioned above, we can simply make the Manager windows integrated popups so they behave exactly like the "Open a project" windows.

**Comment by Wano-k** [comment]
This is a wanted behavior. It was done for avoiding main window async issues such as when you are editing tileset in the datas manager. Your changes only apply when you click on "OK". But that could be great to have access to other managers on the toobar while editing something in another pop-up. But I think that the current behavior is not considered as a problem.

**Comment by hsandt** [comment]
I understand that I cannot work with the main window while a popup is active, but cannot we simply redirect the click on the main window in the background to popup? Just like #37 I'm not expecting any architectural change, only UI event handling change.

@Banbury you mentioned that some Windows applications had the behaviour of not focus onto the popup when clicking outside; can you give me the name of these apps so I can test them, and see if the context is identical or if there are some variations?

**Comment by Banbury** [comment]
@hsandt Sorry I'm unable reproduce, what I did the last time. Maybe I misread the OP.

**Comment by hsandt** [comment]
Can reproduce in latest develop today (2020-07-08).
Ask me anytime on Discord (@Leyn) for a video streaming (I can probably make a GIF but not sure if it would be too clear without the sound; or I can capture an mp4 if you prefer).
