### ISSUE TITLE
Occasional crash when using Datas Manager > Tilesets

### ISSUE THREAD

**Issue by hsandt** [RPG-Paper-Maker/RPG-Paper-Maker#39]
RPG Paper Maker editor sometimes crashes when using the Datas Manager > Tilesets.

I have yet to find a perfect repro.

Version: v0.5.3

Crash occurrences: 2

* after playing with the main view (edit tile coordinates, select another, zoom, try to pane with shift+scroll…) 
* after opening the tile collection view (Auto-tiles, etc.), opening the tile file browser, trying to select a file (but none was available), and clicking Cancel

**Comment by hsandt** [comment]
Cannot reproduce on Linux Ubuntu.
Will try again on Windows.

**Comment by Wano-k** [comment]
I have crash when canceling picture change of the tileset and then mouse hover the collisions preview (in all platforms). I know why I'm having this, I will have a look on this for the next release.

**Comment by Wano-k** [comment]
Corrected for 1.1.1.
