### ISSUE TITLE
Crash when clicking "Change maximum…" in Systems Manager > Battle maps 

### ISSUE THREAD

**Issue by hsandt** [RPG-Paper-Maker/RPG-Paper-Maker#40]
OS: Windows 10
Version: v0.5.3

**Repro**

1. Open Management > Systems Manager > Battle maps
2. In the Currencies section, click `Change maximum...`

**Result**

100% crash

**Expected**

Open the popup that allows to to change the number of Currencies defined.

**Notes**

No crash on Linux also for v0.5.3, expected behavior happens.
100% crash when clicking Change maximum… in Systems Manager > Battle maps

**Comment by Wano-k** [comment]
Yep it's due  to the fact that this version was pushed when I was starting to develop the battles feature. Just forgot to disable this option ahah. This will be corrected in the next version. :)

**Comment by hsandt** [comment]
There is no currency section anymore, so I guess we can consider it fixed.
