### ISSUE TITLE
[Question] Why I Have This Error Message When Opening RPM After Upgrading to Ubuntu 18.04.1 from Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by ditokp** [RPG-Paper-Maker/RPG-Paper-Maker#43]
After I upgrade my laptop from Ubuntu 16.04 LTS to 18.04.1 LTS, I'm not trying or opening RPG Paper Maker at all. And then after a few months after upgrading and updating system, today, I'm opening RPG Paper Maker and I have this error message in the terminal. The app is running normal. I don't understand the error message, please explain it to me if you not busy.

This is the error message:
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error

My system specs:
OS : Ubuntu 18.04 LTS 64-Bit
Graphics : Intel SandyBridge Mobile

Thank you very much for reading and answering my question.

**Comment by afaur** [comment]
Looks like someone using the wkhtmltopdf project had this issue:
 - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001#issuecomment-300996664

This seems to have resolved it:
 - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001#issuecomment-309673453

@ditokp 
 - Is it possible that you might need to install the package: libssl1.0-dev ?

**Comment by ditokp** [comment]
Hello @afaur , sorry for late reply. Now I move to Lubuntu 18.04.1 LTS and in Lubuntu have that error message too and can't open RPM. I try installing that package and I can open the app again, thank you very much.

But I have this error message in the Terminal:

`QApplication: invalid style override passed, ignoring it.`

**Comment by krille-chan** [comment]
I have the same problem but on Ubuntu 22.04 and on 23.04 the package mentioned in the workaround does no longer exist. Do someone has a newer workaround? I even can't start the steam version
