### ISSUE TITLE
[Export] Allow exporting to new and existing directory

### ISSUE THREAD

**Issue by hsandt** [RPG-Paper-Maker/RPG-Paper-Maker#44]
**Current behavior**

When exporting to a folder $ExportPath already containing ${ProjectName}-Test${PLATFORM}, exporting fails with Error:

> The directory ${ProjectName}-Test${PLATFORM} already exists.

However, exporting the first time to $ExportPath will create such a folder. In other words, the second time you export in the same folder, the UI simply block you.

![rpg paper maker v0 5 3 - export directory already exists](https://user-images.githubusercontent.com/1067772/48971604-d269e400-f013-11e8-996e-363fdfe382cc.png)

I have also tried to target another folder such as ${ExportPath}2, but then export fails with Error:

> The path location doesn't exist.

![rpg paper maker v0 5 3 - export on new directory fails as location doesnt exist](https://user-images.githubusercontent.com/1067772/48971606-d5fd6b00-f013-11e8-831e-50bb1e9f6863.png)

**Suggested behavior**

When trying to export to an existing folder:
- it would prompt you to overwrite the existing folder
- you can check an option "don't ask again" so you automatically overwrite next time (you could toggle this off in the Options)

When trying to export to a new folder:
- the new folder is created, so the subfolder ${ProjectName}-Test${PLATFORM} can be created inside

Bonus:
- allow to prefix export subfolder with current version so you can keep the previous build versions, and you only overwrite the current version for smaller iterations (e.g. ${ProjectName}-Test${PLATFORM}-v${MAJOR}.${MINOR})

**Behavior of similar apps**

- Unity will simply overwrite any existing folder with the same name.

**Comment by Wano-k** [comment]
Added to the next fixes to complete for the next release, thanks!

**Comment by Wano-k** [comment]
Done for 1.1.1 next release (except for "don't ask again option").
