### ISSUE TITLE
[Bugs] Version 1.0.0 Windows: Sprite Walls -> NaN out of range

### ISSUE THREAD

**Issue by H4banero** [RPG-Paper-Maker/RPG-Paper-Maker#48]
I added the default sprite_wall to the tileset in the data manager. After that, I get the following error message when I run (test it):

file:Content/Datas/Scripts/System/system-picture.js - line: 144 -> NaN out of range

**Comment by Wano-k** [comment]
Thanks, this will be corrected for 1.0.1.
