### ISSUE TITLE
[Bug] Version 1.0.1 Mapproperties - change squaresize

### ISSUE THREAD

**Issue by H4banero** [RPG-Paper-Maker/RPG-Paper-Maker#49]
Menu: Managment -> Systemsmanager -> change squaresize in mapproperties from16px to 32px or 64px

Error 32px square size:
file:Content/Datas/Scripts/System/system-picture.js - line:144 -> 4.5 out of range

Error 64px square size:
file:Content/Datas/Scripts/System/system-picture.js - line: 247 -> 0.25 out of range

**Comment by Wano-k** [comment]
I guess that's a parsing issue with the autotiles / walls. Is it OK if you remove it from the tileset ? If it's that I should return a clear error so the user understand that he has a wrong autotile format, or display it anyway.

**Comment by H4banero** [comment]
Yes, if i remove the graphic from autotile section the error disappears.

**Comment by Wano-k** [comment]
Corrected for next coming release (1.1.1). No more error messages.
