### ISSUE TITLE
Add build status indicators to `README.md`

### ISSUE THREAD

**Issue by afaur** [RPG-Paper-Maker/RPG-Paper-Maker#5]
For visibility of the status of automated builds it may be helpful to add status badges to the `README.md` file.

The badge for `Travis-CI`
[![Travis Build Status](https://travis-ci.org/Wano-k/RPG-Paper-Maker.svg?branch=develop)](https://travis-ci.org/Wano-k/RPG-Paper-Maker)

The Badge code for AppVeyor should be something like:
[![AppVeyor Build Status](https://ci.appveyor.com/project/Wano-k/branch/develop?svg=true)](https://ci.appveyor.com/project/Wano-k/RPG-Paper-Maker)
after AppVeyor is setup for this repository.

**Comment by afaur** [comment]
May want to have badges for both `develop` and `master` on the `readme` after the `.travis.yml` and `.appveyor.yml` additions make it to that branch.

**Comment by Wano-k** [comment]
Added for develop branch! Is it necessary for master branch, by supposing that merges to master are done only with correct develop builds (and no direct pull request to master can be done)?

**Comment by afaur** [comment]
No, it should not be necessary if that is the workflow.
