### ISSUE TITLE
[Bug] v1.0.1 Mapproperties Squaresize bigger 32px

### ISSUE THREAD

**Issue by H4banero** [RPG-Paper-Maker/RPG-Paper-Maker#50]
If I set the square size larger than 32px in mapproperties, then I get an out of range error despite removing the default autotiles. 32px works. I tried 48px and 64px.

The default hero sprite is then no longer displayed in the level. At 32px it is.
Are 48px square size also supported or 16px/32px/64px/etc.?

Is it a bug or a user error? I do not add anything to the level.

**Comment by Wano-k** [comment]
Check https://github.com/RPG-Paper-Maker/RPG-Paper-Maker/issues/49.
