### ISSUE TITLE
Ship `Contents` folder as a resource pack separate from binary releases

### ISSUE THREAD

**Issue by afaur** [RPG-Paper-Maker/RPG-Paper-Maker#6]
> Since the `Contents` folder is a resource pack that is used by the Engine binary, but may not have changed since a previous release of the program it might be best to create a git hook that will publish the Contents folder separately from the tag based releases.

- > I don't know if it's really necessary here, but why not. How would it work for the contributors? How could we organize that?

Anytime modifications are made to `Engine/Contents` and they are merged in by Pull Request the individual would also update a file `Engine/Contents/CHANGELOG.md` in that same Pull Request.

When a Developer creates a new `tag` locally and pushes that `tag` up to github a githook script would execute locally. It would `grep` the `Engine/Contents/CHANGELOG.md` file looking for a `semver` entry (example: **v0.1.1** - Added a 2D character texture) to that matches the current `tag` that is being pushed. If it finds an exact match then that means we need to add a new version of the `Engine/Contents` folder along with the binaries for this new `tag`.

We can get access to the current tag being pushed based on [this](https://stackoverflow.com/questions/5809910/how-do-i-react-to-new-tags-in-git-hooks#answer-5810488)

**Comment by Wano-k** [comment]
The organization have now a lot of different separated repos including Dependencies and Basic Ressources!
