### ISSUE TITLE
[Ubuntu] RPG Paper Maker crashing after a few seconds of opening a project

### ISSUE THREAD

**Issue by ghost** [RPG-Paper-Maker/RPG-Paper-Maker#63]
I've been using rpg paper maker for a little while now, and a week ago my computer crashed while i was using rpg paper maker. Now, after opening any project, and waiting a few seconds, it crashes. i had some good progress on a game so its really frustrating me. the command line always just says "segmentation fault"

**Comment by Wano-k** [comment]
That's really weird! So even when you create a new project it crashes? If so, could you send the folder containing `run.sh` file? There will be way to have your datas going back no worries!

**Comment by ghost** [comment]
https://drive.google.com/file/d/1HZflWHwnAmYcIDRjsMqPmXgB-1GJK-IO/view?usp=sharing
here you go.

**Comment by Wano-k** [comment]
Closed for inactivity, you can re-open if you still have the issue.
