### ISSUE TITLE
[Bug] Field in [New project->Location->Browse] is not loaded

### ISSUE THREAD

**Issue by XiaoMingXD** [RPG-Paper-Maker/RPG-Paper-Maker#65]
When you creating new project, you may need to select location by using the button on the right .
![image](https://user-images.githubusercontent.com/44926319/86096165-86332f80-bae5-11ea-9b28-4d82e164b778.png)
The new dialog's title does not look right. The field is not loaded correctly.
![image](https://user-images.githubusercontent.com/44926319/86095645-d362d180-bae4-11ea-8307-3cc2a5e3501b.png)

**Comment by Wano-k** [comment]
Thanks for reporting, this will be corrected for next patch (1.5.5)!
