### ISSUE TITLE
[Bug][Windows] When try to load an Empty save, There's an error dialog came out.

### ISSUE THREAD

**Issue by XiaoMingXD** [RPG-Paper-Maker/RPG-Paper-Maker#67]
When I try to load an empty save in 【Load Game】, an error dialog like the image down below jump out. And when I click the OK button on the error dialog, the entire game flashed back (the editor is fine). 
![image](https://user-images.githubusercontent.com/44926319/86364566-e9ba8a00-bcaa-11ea-81a4-0e704dec6169.png)
**BTW**, I encountered tons of issues with the translations file. Such as I can't find the entry of most of the word in the Inventory page, like [Inventory],[Consumables]. Some of those even if they can be found, it does not work, like [All] (line 387),[Ingredient] (line 919),[Weapons] (line 130),[Armors] (line 131). I'm not sure should I open a new issue for those or not if I find more about that translate thing.
![image](https://user-images.githubusercontent.com/44926319/86367216-3fdcfc80-bcae-11ea-87b3-88d4e6512870.png)

**Comment by Wano-k** [comment]
Thanks, this will be also corrected for 1.5.5.

For translations, that's a normal thing, the features for changing it will be available later!

**Comment by XiaoMingXD** [comment]
I have not tested the 【Load Empty save】 thing on other platforms because I don't have any those devices. You may need to look into it to see if they have the same issue as Windows.

**Comment by Wano-k** [comment]
It's OK for every platform. :)
